# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,jquery.alerts.css,jquery-ui-1.8.5.custom.css, jquery.jqplot.css]

  javascripts:    [jquery.js, jquery-ui-1.8.5.custom.min.js, jquery.alerts.js, jquery.jqplot.js, jqplot.highlighter.min.js, jqplot.pieRenderer.min.js]

  has_layout:     true
  layout:         layout
