<?php


/**
 * Skeleton subclass for representing a row from the 'admin' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 27 17:43:37 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Admin extends BaseAdmin {

    public function  __toString()
    {
        return $this->getName();
    }

    public function getStringLevel()
    {
        $c = new Criteria();
        $id = $this->idlevel;
        $c->add(LevelPeer::NAME,$id);

        return "toto";
    }

} // Admin
