<?php



/**
 * Skeleton subclass for performing query and update operations on the 'admin' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue Sep 28 15:53:16 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class AdminQuery extends BaseAdminQuery {

    /*
     * @param Name of the admin we search
     * @return admin object
     *
     * Allow to find an admin with his name
     */
    public static function getByName($name)
    {
        return self::create()
                ->filterByName($name)
                ->findOne();
    }

    /*
     * @return array of admin
     *
     * Allow to find an array with admins who've a level 11 ie there are super-admin
     */
    public static function listAdmin5()
    {
        return self::create()
                ->filterByIdlevel("11")
                ->find();
    }


} // AdminQuery
