<?php



/**
 * Skeleton subclass for performing query and update operations on the 'connection' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Oct 27 09:36:03 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ConnectionPeer extends BaseConnectionPeer {

    public static function getLastOrder()
    {
        $con = ConnectionQuery::create()
          ->orderByOrder('desc')
          ->findOne();

        return $con;
    }

} // ConnectionPeer
