<?php



/**
 * Skeleton subclass for performing query and update operations on the 'connection' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Oct 27 09:36:03 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ConnectionQuery extends BaseConnectionQuery {

    /*
     * @return array of connection object
     * 
     * Allow to find connection objects which are in stand-by (waiting = 1)
     */
    public function filterByConnectedUser()
    {
      return self::create()
                ->filterByWaiting('1')
                ->find();
    }

    public function filterByBefore()
    {
      return $this->filterByWaiting('1')
                ->filterByCreatedAt(array('max' => time()-1));
    }

    /*
     * @param id of a user
     * @return connection object
     *
     * Allow to find a connection for a special user thanks its id
     * 
     */
    public function filterByUserConnect($idUser)
    {
       return $con = ConnectionQuery::create()
                ->filterByIduser($idUser)
                ->filterByBefore();
    }
} // ConnectionQuery
