<?php



/**
 * Skeleton subclass for performing query and update operations on the 'lend_product' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Fri Nov  5 15:03:16 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class LendProductPeer extends BaseLendProductPeer {

} // LendProductPeer
