<?php



/**
 * Skeleton subclass for performing query and update operations on the 'option_ip' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.5 on:
 *
 * Fri Dec  3 10:54:11 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class OptionIpQuery extends BaseOptionIpQuery {

    public static function exists($ip)
    {
        $is = OptionIpQuery::create()
                ->filterByAddress($ip)
                ->find();

        if(count($is) > 0)
            return true;
        else
            return false;
    }

} // OptionIpQuery
