<?php



/**
 * Skeleton subclass for performing query and update operations on the 'option' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue Sep 28 15:53:16 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class OptionQuery extends BaseOptionQuery {

    /*
     * @return boolean
     *
     * Allow to know if option of mail is active (the last choice)
     */
    public static function mailIsActive()
    {
        $isActive = self::create()
          ->orderById('desc')
          ->findOne();

        if($isActive->getAutomail() == '1')
          return true;
        else
          return false;
    }
    
} // OptionQuery
