<?php



/**
 * Skeleton subclass for performing query and update operations on the 'product_categ' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Wed Sep 29 09:33:59 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ProductCategQuery extends BaseProductCategQuery {

    /*
     * @param id of the category
     *
     * Return of number of products in this category.
     */
    public  function countProductsInCateg($idCateg)
    {
        $result = $this->filterByCateg($idCateg)
                  ->find();
        
        return count($result);
    }

    /*
     * @param id of the category and the date where is created.
     */
    public static function nbProductOneCateg($idCateg,$date)
    {
        return self::create()
                    ->filterByIdCateg($idCateg)
                    ->useProductQuery()
                        ->where($date+(3600*24).'> UNIX_TIMESTAMP(Product.CreatedAt) OR UNIX_TIMESTAMP(Product.CreatedAt) = '.$date)
                    ->endUse()
                    ->count();
    }

} // ProductCategQuery
