<?php



/**
 * Skeleton subclass for performing query and update operations on the 'student_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue Sep 28 15:53:16 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class StudentUserQuery extends BaseStudentUserQuery {

    /*
     * @param id of the student and id of the user
     * @return boolean
     *
     * Verify if this student is already on the list of the referant
     */
    static function alreadyExist($idUser,$idR)
    {
        $rep = self::create()->filterByIdStudent($idUser)->filterByIdUser($idR)->findOne();
        if(count($rep) > 0)
            return true;
        else
            return false;
    }

} // StudentUserQuery
