<?php



/**
 * Skeleton subclass for performing query and update operations on the 'student' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.3 on:
 *
 * Tue Sep 28 15:53:16 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class StudentQuery extends BaseStudentQuery {

    /*
     * @return an array of student objects
     *
     * Find all students.
     */
    protected static function getStudent()
    {
        return StudentQuery::create()
                        ->find();
    }
} // StudentQuery
